//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_Mem_Quan_Ly_Can_Xe_Tai.Bussiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuCan
    {
        public long Id { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoXe { get; set; }
        public string KhachHang { get; set; }
        public string Loaihang { get; set; }
        public Nullable<System.DateTime> NgayCan1 { get; set; }
        public Nullable<System.DateTime> NgayCan2 { get; set; }
        public Nullable<decimal> TrongLuongCan1 { get; set; }
        public Nullable<decimal> TrongLuongCan2 { get; set; }
        public Nullable<decimal> TrongLuongHang { get; set; }
        public string XuatNhap { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpatedUser { get; set; }
    }
}
