//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_Mem_Quan_Ly_In_Tem.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeDetail
    {
        public long BarcodeID { get; set; }
        public Nullable<System.Guid> BarcodeUnique { get; set; }
        public string BarcodeString { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string ItemName { get; set; }
        public string GoldType { get; set; }
        public string GoldSign { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> StoneWeight { get; set; }
        public Nullable<decimal> GoldWeight { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierStandardNo { get; set; }
        public string Origin { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string TemplatePath { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeteletedUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CompanyStandardNo { get; set; }
        public string WeightDisplayFormat { get; set; }
    }
}
