//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_Mem_Quan_Ly_In_Tem.ModelEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrintBarcodeEntities : DbContext
    {
        public PrintBarcodeEntities()
            : base("name=PrintBarcodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<BarcodeDetail> BarcodeDetails { get; set; }
        public virtual DbSet<BarcodeTemplate> BarcodeTemplates { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
    }
}
